[Table of Contents](table_of_contents.ipynb)

# Topic 20.  Eigenvalues and Eigenvectors
Author: Mat Haskell - mhaskell9@gmail.com

##  Introduction
Eigen values and eigen vectors are very cool and show up all over the place. Eigenvalues exist generally for linear operators, but this notebook will just look at matrices. The basic idea is that matrix multiplication is turned into scalar multiplication. This seems strange since matrix multiplication is complex and you can't always envision the result by just looking at the equation. Matrices can be used to project onto a lower dimensional space and rotate a vector, which is how they are commonly used. However, when multiplying a matrix by one of its eigenvectors, that vector will just be scaled by the value of the corresponding eigenvalue. The eigenvector can grow, shrink, and flip directions (i.e. eigenvalues can be negative). Eigenvalues can even be zero, in which case the eigenvector multiplied by the matrix will be scaled down to zero as well.

__PREFACE THIS__

The physical meaning of eigenvalues and eigenvectors is also cool. The eigenvectors are the principal axes of the matrix. This means that the eigenvectors of a stress/strain tensor are the principal axes and the eigenvalues are the principal stresses/strains. Another example is with an inertia tensor. If there are cross terms (elements off the main diagonal in the inertia tensor) the eigenvectors are the axes of the object that get rid of the cross terms. This means you can find the x, y, and z axes where there is symmetry and no inertia in any other direction.

$\newcommand{\real}{\mathbb{R}}$
$\newcommand{\complex}{\mathbb{C}}$
$\newcommand{\script}[1]{\mathcal{#1}}$
$\newcommand{\chi}{\script{X}}$
## Explanation of the theory
Eigenvalues only exist for square matrices.
$$A\in \complex^{n\times n}$$

Let $x\in\complex^{n\times1}$ be an eigenvector of A and $\lambda\in\complex$ be the corresponding eigenvalue of A, then converting matrix multiplication into scalar multiplication yields the equation:
$$Ax=\lambda x$$

Here are the formal definitions for eigen pairs:

__Def:__ $(\lambda,x)$ is a __right eigen pair__ if $Ax=\lambda x$.

__Def:__ $(\lambda,x)$ is a __left eigen pair__ if $x^HA^H=\lambda x^H$.

Most of the time we deal with right eigen pairs. So here is how to actually solve for the eigenvalues. Before any computational work, we need to rearrange the equation $Ax=\lambda x$ into a useful form.

- Get everything onto 1 side of the equation (it doesn't matter which side):

$$Ax-\lambda x=0$$

- Multiply x by identity (which doesn't change it):

$$Ax-\lambda Ix=0$$

- Factor out the x:

$$(A-\lambda I)x=0$$

__Note:__ some textbooks write it as $(\lambda I-A)x=0$, but they are equivalent.

We can see that $x\in\mathcal{N}(A-\lambda I)$. Since there is a non-trivial null space we know that $(A-\lambda I)$ is not full rank, which implies that $det(A-\lambda I)=0$. We will use this fact to solve for the eigenvalues of A.

### Finding the eigenvalues of a matrix
Here are the computational steps for finding the eigenvalues of A:

1. Start with the equation we just derived:

$$det(A-\lambda I)=0$$

$$
\Rightarrow
\left|
\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{pmatrix}
-
\begin{pmatrix}
\lambda & 0 & \cdots & 0\\
0 & \lambda & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & \lambda
\end{pmatrix}
\right|
=0
$$

$$
\Rightarrow
\left|
\begin{pmatrix}
a_{11}-\lambda & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22}-\lambda & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn}-\lambda
\end{pmatrix}
\right|
=0
$$

2. Take the determinant. This will give the characteristic polynomial of A, $\chi_A(\lambda)$, and characteristic equation of A, $\chi_A(\lambda)=0$. Let $\alpha_i$ be a scalar, then the charateristic polynomial can be written as:

$$\chi_A(\lambda)\triangleq\lambda^n+\alpha_{n-1}\lambda^{n-1}+\cdots+\alpha_1\lambda+\alpha_0=0$$

3. Find the roots of the characteristic polynomial, which are the eigenvalues. By the fundamental theorem of algebra, we know that the characteristic polynomial will have n roots. This means that there are going to be n eigenvalues, although some of them may be repeated. When eigenvalues are repeated, there are p distict eigenvalues, where p does not count a repeated eigenvalue more than once. There are software libraries that can solve the roots of a polynomial, or you can do it by hand with polynomial division. This involves some guessing and checking because you have to guess a root, do the polynomial division, and check if it worked (and repeat). Since software tools exist, I would suggest not finding the roots by hand. In fact, I wouldn't even find the eigenvalues or eigenvectors by hand since Matlab and Python already have functions for them. But hopefully you can see how it can be done from this notebook.

__Note:__ we can write $\chi_A$ with all of the eigenvalues factored out (which would be the result of polynomial division):

$$\chi_A(\lambda)=(\lambda-\lambda_{1})(\lambda-\lambda_{2})\cdots(\lambda-\lambda_{n})=\Pi_{i=0}^n(\lambda-\lambda_i)$$

__Def:__ Algebraic multiplicity, $m_i$, of $\lambda_i$ is the number of times it is repeated. So $\chi_A$ can be written like this:
$$\chi_A(\lambda)=(\lambda-\lambda_{1})^{m_1}(\lambda-\lambda_{2})^{m_2}\cdots(\lambda-\lambda_{p})^{m_p},\ \ \ \ \ p\leq n$$

### Finding the eigenvectors of a matrix
After finding the roots/eigenvalues, we can solve for the eigenvectors by plugging in each eigenvalue into the equation $(A-\lambda_iI)x=0$. You are just solving for the null space of $(A-\lambda I)$. 

__Note:__ any linear combination of vectors from $\mathcal{N}(A-\lambda I)$ are also eigenvectors. Because any scalar multiple of an eigenvector is also an eigenvector, most software libraries will return the eigenvectors with a norm of 1.

### Example:
Find the eigenvalues and eigenvectors of A by following the steps above.
$$A=\begin{pmatrix}4 & -2\\5 & -7\end{pmatrix}$$

1. First set $det(A-\lambda I)=0$:

$$
\left|
\begin{pmatrix}
4-\lambda & -2\\
5 & -7-\lambda
\end{pmatrix}
\right|
=0
$$

2. Take the determinant to find the characteristic equation:

\begin{eqnarray}
\chi_A(\lambda)&=&(4-\lambda)(-7-\lambda)+10=0\\
&=&\lambda^2+3\lambda-18=0
\end{eqnarray}

3. Find the roots/eigenvalues.

$$\chi_A(\lambda)=(\lambda+6)(\lambda-3)$$

The order of assigning $\lambda_1$ and $\lambda_2$ doesn't really matter. I will use these:
$$\lambda_1=3$$ 
$$\lambda_2=-6$$

Neither of these are repeated, so the algebraic multiplicity of both are just 1.
$$m_1=1$$ 
$$m_2=1$$

Let's continue with the example and find the eigenvectors of A.
- For $\lambda_1=3$:

\begin{eqnarray}
\begin{pmatrix}
4-\lambda & -2\\
5 & -7-\lambda
\end{pmatrix}
\begin{pmatrix}x_1\\x_2\end{pmatrix}&=&\begin{pmatrix}0\\0\end{pmatrix} \\
\begin{pmatrix}
4-3 & -2\\
5 & -7-3
\end{pmatrix}
\begin{pmatrix}x_1\\x_2\end{pmatrix}&=&\begin{pmatrix}0\\0\end{pmatrix} \\
\begin{pmatrix}
1 & -2\\
5 & -10
\end{pmatrix}
\begin{pmatrix}x_1\\x_2\end{pmatrix}&=&\begin{pmatrix}0\\0\end{pmatrix}
\end{eqnarray}

Notice that both rows of A when multiplied by x give the same equation:
\begin{eqnarray}
&x_1&-2x_2=0 \\
\Rightarrow &x_1&=2x_2
\end{eqnarray}
Now we can solve for x:
$$
x=
\begin{pmatrix}2x_2 \\ x_2\end{pmatrix}=
\begin{pmatrix}2 \\ 1\end{pmatrix}x_2
$$
An eigenvector associated with $\lambda_1$, $\mathbf{v_1}$, is any scalar multiple of $\begin{pmatrix}2 \\ 1\end{pmatrix}$.

- For $\lambda_2=-6$:

\begin{eqnarray}
\begin{pmatrix}
4-\lambda & -2\\
5 & -7-\lambda
\end{pmatrix}
\begin{pmatrix}x_1\\x_2\end{pmatrix}&=&\begin{pmatrix}0\\0\end{pmatrix} \\
\begin{pmatrix}
4+6 & -2\\
5 & -7+6
\end{pmatrix}
\begin{pmatrix}x_1\\x_2\end{pmatrix}&=&\begin{pmatrix}0\\0\end{pmatrix} \\
\begin{pmatrix}
10 & -2\\
5 & -1
\end{pmatrix}
\begin{pmatrix}x_1\\x_2\end{pmatrix}&=&\begin{pmatrix}0\\0\end{pmatrix}
\end{eqnarray}

Notice that both rows of A when multiplied by x give the same equation:
\begin{eqnarray}
&5x_1&-x_2=0 \\
\Rightarrow &x_2&=5x_1
\end{eqnarray}
Now we can solve for x:
$$
x=
\begin{pmatrix}x_1 \\ 5x_1\end{pmatrix}=
\begin{pmatrix}1 \\ 5\end{pmatrix}x_1
$$
An eigenvector associated with $\lambda_2$, $\mathbf{v_2}$, is any scalar multiple of $\begin{pmatrix}1 \\ 5\end{pmatrix}$.

### Eigenvalue decomposition
The eigenvalue decomposition of A is as such:
$$A=S\Lambda S^{-1}$$

Where,
$$
\Lambda=diag([\lambda_1, \lambda_2, \cdots, \lambda_n])
=
\begin{pmatrix}
\lambda_1 & 0 & \cdots & 0 \\
0 & \lambda_2 & \cdots & 0 \\
\vdots & \vdots & \ddots & 0 \\
0 & 0 & \cdots & \lambda_n
\end{pmatrix}
$$

$$
S=\begin{pmatrix}
\mathbf{v_1} & \mathbf{v_2} & \cdots & \mathbf{v_n}
\end{pmatrix}
$$

__Note:__ it does not matter in which order the eigenvalues are placed to form $\Lambda$. However, for $A=S\Lambda S^{-1}$ to be true, the position of the column of $\lambda_i$ must match the position of the column of $\mathbf{v_i}$ (where $\mathbf{v_i}$ is an eigenvector corresponding to $\lambda_i$).

__Def:__ Geometric multiplicity, $q_i$, of $\lambda_i$ is the number of linearly independent eigenvectors that can be formed from $\lambda_i$. Also, $1\leq q_i\leq m_i$.
This means at least 1 eigenvector can be formed from every eigenvalue, but at most $m_i$. For example: if an eigenvalue is repeated 3 times, there will be at most 3 corresponding linearly independent eigenvectors but at least 1 eigenvector.

The geometric multiplicity of an eigenvalue is a very important concept for eigenvalue decomposition. In order to perform the eigenvalue decomposition, as described above where $A=S\Lambda S^{-1}$, the geomectric multiplicity must be equal to the algebraic multiplicity for each eigenvalue. i.e.

$$m_i=q_i\ \ \ \forall\lambda_i$$

This means that however many times an eigenvalue is repeated, there must be that same number of linearly independent eigenvectors derived from that eigenvalue. Otherwise, there isn't enough eigenvectors to fill the columns of S.

When $m_i\neq q_i$, there is a process to find what are called generalized eigenvectors to fill up the missing columns of S. When this happens, $\Lambda$ is replaced with $J$ and is not strictly diagonal. This is called the Jordan form and is a topic for another day.

### Fun Facts

- If eigenvalues are complex, the corresponding eigenvectors will be complex. 
- If an eigenvalue is complex, its complex conjugate will also be an eigenvalue. 
- If an eigenvector is complex, its complex conjugate will also be an eigenvector.
- Symmetric matrices have real eigenvalues.
- For a positive definite matrix $\Leftrightarrow$ all eigenvalues will be positive ($\lambda_i>0$).
- For a positive semi-definite matrix $\Leftrightarrow$ all eigenvalues will be non-negative ($\lambda_i\geq0$).
- For a negative semi-definite matrix $\Leftrightarrow$ all eigenvalues will be non-positive ($\lambda_i\leq0$).
- For a negative definite matrix $\Leftrightarrow$ all eigenvalues will be negative ($\lambda_i<0$).
- The trace of a matrix equals the sum of its eigenvalues ($trace(A)=\sum\lambda_i$).
- The determinant of a matrix equals the product of its eigenvalues ($det(A)=\Pi\lambda_i$).
- Eigenvectors of a matrix are all linea

## Simple Numerical Examples

### First let's verify the example from above.


In [22]:
import numpy as np

A = np.array([[4,-2],
              [5,-7]])
l1 = 3
l2 = -6
v1 = np.array([[2],
               [1]])
v2 = np.array([[1],
               [5]])

print(np.trace(A))

# check that Ax-lx=0
# note that numerical precision might limit this to being very close to true
print('Test 1:')
if np.array_equal(A@v1, l1*v1):
    print('v1 and l1 are a right eigen pair! \n')
else:
    print('error \n')
    
print('Test 2:')
if np.array_equal(A@v2, l2*v2):
    print('v2 and l2 are a right eigen pair! \n')
else:
    print('error \n')
    
# eigenvalue decomposition
L = np.diag([l1, l2])
S = np.concatenate((v1,v2), axis=1)
S_inv = np.linalg.inv(S)

# test that it works
print('Test 3:')
if np.array_equal(A, S@L@S_inv):
    print('A = S*L*S_inv! \n')
else:
    print('error \n')

# now let's test that the order doesn't matter
L = np.diag([l2, l1])
S = np.concatenate((v2,v1), axis=1)
S_inv = np.linalg.inv(S)

print('Test 4:')
if np.array_equal(A, S@L@S_inv):
    print('It still works when the order is switched! \n')
else:
    print('error \n')

-3
Test 1:
v1 and l1 are a right eigen pair! 

Test 2:
v2 and l2 are a right eigen pair! 

Test 3:
A = S*L*S_inv! 

Test 4:
It still works when the order is switched! 



### Now let's see how to get the eigenvalues through code

In [23]:
import numpy as np

A = np.array([[2.,0.,0.],
              [0.,3.,4.],
              [0.,4.,9.]])

vals,vecs = np.linalg.eig(A)

print('Eigenvalues are %d, %d, and %d.' % (vals[0],vals[1],vals[2]))
print('The eigenvector corresponding to %d is:'%vals[0])
print(vecs[:,0][:,None])
print('The eigenvector corresponding to %d is:'%vals[1])
print(vecs[:,1][:,None])
print('The eigenvector corresponding to %d is:'%vals[2])
print(vecs[:,2][:,None])

# check if Ax-lx=0
if np.array_equal(A@vecs[:,0], vals[0]*vecs[:,0]) :
    print('success')
else:
    print('fail')
if np.array_equal(A@vecs[:,1], vals[1]*vecs[:,1]) :
    print('success')
else:
    print('fail')
if np.array_equal(A@vecs[:,2], vals[2]*vecs[:,2]) :
    print('success')
else:
    print('fail')
    
# A@vecs[:,1] - vals[1]*vecs[:,1]

# Eigenvalue decomposition
S = vecs
Lambda = np.diag([vals[0],vals[1],vals[2]])
S_inv = np.linalg.inv(S)

# Check that A = S*Lambda*S_inv
print('A - S*Lambda*S_inv = ')
print(A - S@Lambda@S_inv)

Eigenvalues are 11, 1, and 2.
The eigenvector corresponding to 11 is:
[[0.        ]
 [0.4472136 ]
 [0.89442719]]
The eigenvector corresponding to 1 is:
[[ 0.        ]
 [ 0.89442719]
 [-0.4472136 ]]
The eigenvector corresponding to 2 is:
[[1.]
 [0.]
 [0.]]
success
fail
success
A - S*Lambda*S_inv = 
[[0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 4.4408921e-16 0.0000000e+00]
 [0.0000000e+00 4.4408921e-16 0.0000000e+00]]


## An Engineering Application
Ideas
- Inertia tensor, find axes where there are no cross terms
- Differential equation or difference equation (poles of the system show response)
- Rotation matrix (eigenvalues will be 1, $e^{j\theta}$, $e^{-j\theta}$ and eigenvector corresponding to 1 is the axis of rotation)

Provide a more sophisticated example showing one engineering example of the topic, complete with python code.