[Table of Contents](table_of_contents.ipynb)

# Topic 20.  Eigenvalues and Eigenvectors
Author: Mat Haskell - mhaskell9@gmail.com

##  Introduction
Eigen values and eigen vectors are very cool and show up all over the place. Eigenvalues exist generally for linear operators, but this notebook will just look at matrices. The basic idea is that matrix multiplication is turned into scalar multiplication. This seems strange since matrix multiplication is complex and you can't always envision the result by just looking at the equation. Matrices can be used to project onto a lower dimensional space and rotate a vector, which is how they are commonly used. However, when multiplying a matrix by one of its eigenvectors, that vector will just be scaled by the value of the corresponding eigenvalue. The eigenvector can grow, shrink, and flip directions (i.e. eigenvalues can be negative). Eigenvalues can even be zero, in which case the eigenvector multiplied by the matrix will be scaled down to zero as well.

preface this
The physical meaning of eigenvalues and eigenvectors is also cool. The eigenvectors are the principal axes of the matrix. This means that the eigenvectors of a stress/strain tensor are the principal axes and the eigenvalues are the principal stresses/strains. Another example is with an inertia tensor. If there are cross terms (elements off the main diagonal in the inertia tensor) the eigenvectors are the axes of the object that get rid of the cross terms. This means you can find the x, y, and z axes where there is symmetry and no inertia in any other direction.

$\newcommand{\real}{\mathbb{R}}$
$\newcommand{\complex}{\mathbb{C}}$
$\newcommand{\script}[1]{\mathcal{#1}}$
## Explanation of the theory
Eigenvalues only exist for square matrices.
$$A\in \complex^{n\times n}$$

Let $x\in\complex^{n\times1}$ be an eigenvector of A and $\lambda\in\complex$ be the corresponding eigenvalue of A, then converting matrix multiplication into scalar multiplication yields the equation:
$$Ax=\lambda x$$


__Def:__ $(\lambda,x)$ is a __right eigen pair__ if $Ax=\lambda x$.

__Def:__ $(\lambda,x)$ is a __left eigen pair__ if $x^HA^H=\lambda x^H$.

Most of the time we deal with right eigen pairs. So here is how to actually solve for the eigenvalues.

1. Get everything onto 1 side of the equation (it doesn't matter which side):

$$Ax-\lambda x=0$$

2. Multiply x by identity (which doesn't change it):

$$Ax-\lambda Ix=0$$

3. Factor out the x

$$(A-\lambda I)x=0$$

4. Since $x\in\mathcal{N}(A-\lambda I)$, we know that $(A-\lambda I)$ is not full rank, which implies that its determinant equals 0:

$$det(A-\lambda I)=0$$

$$
\Rightarrow
\left|
\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{pmatrix}
-
\begin{pmatrix}
\lambda & 0 & \cdots & 0\\
0 & \lambda & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & \lambda
\end{pmatrix}
\right|
=0
$$

$$
\Rightarrow
\left|
\begin{pmatrix}
a_{11}-\lambda & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22}-\lambda & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn}-\lambda
\end{pmatrix}
\right|
=0
$$

5. Taking the determinant will give the characteristic polynomial, $\chi_A(\lambda)$, and characteristic equation, 
$\chi_A(\lambda)=0$:

$$\chi_A(\lambda)\triangleq\lambda^n+\alpha_{n-1}\lambda^{n-1}+\cdots+\alpha_1\lambda+\alpha_0=0$$

6. The roots of the characteristic polynomial are the eigenvalues. By the fundamental theorem of algebra, we know that the characteristic polynomial will have n roots. This means that there are going to be n eigenvalues, although some of them may be repeated. Solve for the roots. Note: we can rearrange the characteristic equation to look like this:

$$\chi_A(\lambda)=(\lambda-\lambda_{1})(\lambda-\lambda_{2})\cdots(\lambda-\lambda_{n})$$

__Def:__ Algebraic multiplicity, $m_i$, of $\lambda_i$ is the number of times it is repeated.
$$\chi_A(\lambda)=(\lambda-\lambda_{1})^{m_1}(\lambda-\lambda_{2})^{m_2}\cdots(\lambda-\lambda_{p})^{m_p},\ \ \ \ \ p\leq n$$

After finding the roots/eigenvalues, we can solve for the eigenvectors by plugging in each eigenvalue into the equation $(A-\lambda_iI)x=0$. You are just solving for the null space of $(A-\lambda I)$. Note that any linear combination of vectors from $\mathcal{N}(A-\lambda I)$ are also eigenvectors. Since any scalar multiple of an eigenvector is also an eigenvector, most software libraries will return the eigenvectors with a norm of 1.

Note: If eigenvalues are complex, the corresponding eigenvectors will be complex. When eigenvalues are complex, both complex numbers from the complex conjugate pair will be eigenvalues. Similarly for eigenvectors: if an eigenvector is complex, its complex conjugate will also be an eigenvector.

__Def:__ Geometric multiplicity, $q_i$, of $\lambda_i$ is the number of linearly independent eigenvectors that can be formed from $\lambda_i$. Also, $$1\leq q_i\leq m_i$$
This means at least 1 eigenvector can be formed from every eigenvalue. For example: if an eigenvalue is repeated 3 times, there will be at most 3 corresponding linearly independent eigenvectors but at least 1 eigenvector.


Can also add these concepts:
- Symmetric matrices have real eigenvalues
- Eigenvalue decomposition $S\Lambda S^{-1}$

## Simple Numerical Examples

Provide some simple python code and examples that emphasize the basic concepts.


In [37]:
import numpy as np

A = np.array([[2.,0.,0.],
              [0.,3.,4.],
              [0.,4.,9.]])

vals,vecs = np.linalg.eig(A)

print('Eigenvalues are %d, %d, and %d.' % (vals[0],vals[1],vals[2]))
print('The eigenvector corresponding to %d is:'%vals[0])
print(vecs[:,0][:,None])
print('The eigenvector corresponding to %d is:'%vals[1])
print(vecs[:,1][:,None])
print('The eigenvector corresponding to %d is:'%vals[2])
print(vecs[:,2][:,None])

# check if Ax-lx=0
if np.array_equal(A@vecs[:,0], vals[0]*vecs[:,0]) :
    print('success')
else:
    print('fail')
if np.array_equal(A@vecs[:,1], vals[1]*vecs[:,1]) :
    print('success')
else:
    print('fail')
if np.array_equal(A@vecs[:,2], vals[2]*vecs[:,2]) :
    print('success')
else:
    print('fail')
    
# A@vecs[:,1] - vals[1]*vecs[:,1]

# Eigenvalue decomposition
S = vecs
Lambda = np.diag([vals[0],vals[1],vals[2]])
S_inv = np.linalg.inv(S)

# Check that A = S*Lambda*S_inv
print('A - S*Lambda*S_inv = ')
print(A - S@Lambda@S_inv)

Eigenvalues are 11, 1, and 2.
The eigenvector corresponding to 11 is:
[[ 0.        ]
 [ 0.4472136 ]
 [ 0.89442719]]
The eigenvector corresponding to 1 is:
[[ 0.        ]
 [ 0.89442719]
 [-0.4472136 ]]
The eigenvector corresponding to 2 is:
[[ 1.]
 [ 0.]
 [ 0.]]
success
fail
success
A - S*Lambda*S_inv = 
[[  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   4.44089210e-16   0.00000000e+00]
 [  0.00000000e+00   4.44089210e-16   0.00000000e+00]]


array([[ 2.,  0.,  0.],
       [ 0.,  3.,  4.],
       [ 0.,  4.,  9.]])

## An Engineering Application
Ideas
- Inertia tensor, find axes where there are no cross terms
- Differential equation or difference equation (poles of the system show response)
- Rotation matrix (eigenvalues will be 1, $e^{j\theta}$, $e^{-j\theta}$ and eigenvector corresponding to 1 is the axis of rotation)

Provide a more sophisticated example showing one engineering example of the topic, complete with python code.